name: Tem
on:
  workflow_dispatch:
    inputs:
      cel:
        description: "Enter temperature in cel"
        required: true
        default: "25"
jobs:
  convert-tem:
    runs-on: ubuntu-latest
    steps:
        - name: chechout repository
          uses: actions/checkout@v3
        - name: setup Python
          uses: actions/setup-python@v4
        - name: Run python script
          run: python egf.py  ${{github.event.inputs.celsius}}
